<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Computer database</name>
   <tag></tag>
   <elementGuidId>25b98d4b-329e-4c4a-b0ae-30367d5731c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.fill</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Computer database')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2d518041-56e4-4467-a248-10f0dc31be76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>2ebc2781-0c7a-4ed4-8bc4-8a73b2a26a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/computers</value>
      <webElementGuid>c6a7b351-f9e4-48ac-b38d-d6eae5392e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Computer database</value>
      <webElementGuid>e77bfe8d-cc33-4b0c-8bc7-648625f69066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[@class=&quot;topbar&quot;]/h1[@class=&quot;fill&quot;]/a[@class=&quot;fill&quot;]</value>
      <webElementGuid>ce3b7341-9ae1-44e0-9a99-178b403c40e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Computer database')]</value>
      <webElementGuid>303d94a3-e449-46bc-872f-9780fe9a3893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done !'])[1]/preceding::a[1]</value>
      <webElementGuid>fc5789c3-aade-4480-839c-4da19966e1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Computer database']/parent::*</value>
      <webElementGuid>709f6b89-7b79-46e7-8d93-1924b41aab0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/computers')]</value>
      <webElementGuid>a60ab388-b7b9-4d82-8548-286284969769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>3b3d988c-1491-44c4-aaeb-4ce198c2606f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/computers' and (text() = 'Computer database' or . = 'Computer database')]</value>
      <webElementGuid>2f7fd17f-0f01-49fa-a718-d34a2c1ffdfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
