<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Computer database_searchsubmit</name>
   <tag></tag>
   <elementGuidId>6eaa1b48-fce8-460b-a16d-73f3f3e7b2e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchsubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchsubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e999ba6-ea80-4b23-a15d-420c644397e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7b4ed292-56e5-4a22-80c8-334445591fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchsubmit</value>
      <webElementGuid>3148420a-ca3b-4c30-94c8-e60e11aeae56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Filter by name</value>
      <webElementGuid>d26473ba-9150-4edb-9764-3783627653d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn primary</value>
      <webElementGuid>67522ee7-7cdc-4720-a820-8963c85f99be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchsubmit&quot;)</value>
      <webElementGuid>5731d749-f432-459c-ae62-d82d541bf353</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchsubmit']</value>
      <webElementGuid>efb510de-8a24-476d-b9e0-736ee90591be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='actions']/form/input[2]</value>
      <webElementGuid>2db828c8-5e4f-456c-889e-44526fceb6a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>66d13a2c-e47f-46db-9754-58c788d5b1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'searchsubmit']</value>
      <webElementGuid>f7205d28-0b4d-42ca-9acd-e747e33cd382</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
