<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Choose a company --Apple Inc.Thin_aed4be</name>
   <tag></tag>
   <elementGuidId>459d6044-b3fa-403e-9bc3-95a88b964d07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#company</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='company']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a7f53560-1d90-436c-8c10-fbe2de6351d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>company</value>
      <webElementGuid>99627850-561b-44ae-aea3-fcff234cc107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>company</value>
      <webElementGuid>9ba46286-f987-4869-bf92-ebc21e2a22e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Choose a company --Apple Inc.Thinking MachinesRCANetronicsTandy CorporationCommodore InternationalMOS TechnologyMicro Instrumentation and Telemetry SystemsIMS Associates, Inc.Digital Equipment CorporationLincoln LaboratoryMoore School of Electrical EngineeringIBMAmiga CorporationCanonNokiaSonyOQONeXTAtariAcorn computerTimex SinclairNintendoSinclair Research LtdXeroxHewlett-PackardZemmixACVSSanyoCrayEvans &amp; SutherlandE.S.R. Inc.OMRONBBN TechnologiesLenovo GroupASUSAmstradSun MicrosystemsTexas InstrumentsHTC CorporationResearch In MotionSamsung Electronics</value>
      <webElementGuid>63993655-0202-4b65-ac0d-cf53a48f0e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;company&quot;)</value>
      <webElementGuid>b1909403-ffcc-463a-83ab-9b9fe428ae8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='company']</value>
      <webElementGuid>ea204bb9-b7f0-4ca6-a812-ccc021fffaae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/form/fieldset/div[4]/div/select</value>
      <webElementGuid>07d2aa31-6046-4c1f-8af6-8cfae781a710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company'])[1]/following::select[1]</value>
      <webElementGuid>5e538e4a-dd97-4361-be8c-21ff6314d85c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Date (', &quot;'&quot;, 'yyyy-MM-dd', &quot;'&quot;, ')')])[2]/following::select[1]</value>
      <webElementGuid>d804ba45-f985-425a-a45c-148dea8bcd43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::select[1]</value>
      <webElementGuid>1ee25b3f-cd53-4103-9141-813feca0fdba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>e79e36dc-2b26-4882-befb-682e034931d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'company' and @name = 'company' and (text() = '-- Choose a company --Apple Inc.Thinking MachinesRCANetronicsTandy CorporationCommodore InternationalMOS TechnologyMicro Instrumentation and Telemetry SystemsIMS Associates, Inc.Digital Equipment CorporationLincoln LaboratoryMoore School of Electrical EngineeringIBMAmiga CorporationCanonNokiaSonyOQONeXTAtariAcorn computerTimex SinclairNintendoSinclair Research LtdXeroxHewlett-PackardZemmixACVSSanyoCrayEvans &amp; SutherlandE.S.R. Inc.OMRONBBN TechnologiesLenovo GroupASUSAmstradSun MicrosystemsTexas InstrumentsHTC CorporationResearch In MotionSamsung Electronics' or . = '-- Choose a company --Apple Inc.Thinking MachinesRCANetronicsTandy CorporationCommodore InternationalMOS TechnologyMicro Instrumentation and Telemetry SystemsIMS Associates, Inc.Digital Equipment CorporationLincoln LaboratoryMoore School of Electrical EngineeringIBMAmiga CorporationCanonNokiaSonyOQONeXTAtariAcorn computerTimex SinclairNintendoSinclair Research LtdXeroxHewlett-PackardZemmixACVSSanyoCrayEvans &amp; SutherlandE.S.R. Inc.OMRONBBN TechnologiesLenovo GroupASUSAmstradSun MicrosystemsTexas InstrumentsHTC CorporationResearch In MotionSamsung Electronics')]</value>
      <webElementGuid>8714adf9-2967-4c55-86db-9f22fe0f34d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
