<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_englishjapanese</name>
   <tag></tag>
   <elementGuidId>e338a161-faa6-4971-9187-69a77c54a868</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;account.languagePreference&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='account.languagePreference']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f599462e-4fc4-45c3-9c3e-8a866196c673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account.languagePreference</value>
      <webElementGuid>ecf6f7be-17a8-4c98-a894-019ff6cd048d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			englishjapanese
		</value>
      <webElementGuid>5faa01ac-877f-4e73-8b3d-d026c98c3358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Catalog&quot;)/form[1]/table[3]/tbody[1]/tr[1]/td[2]/select[1]</value>
      <webElementGuid>ffa80f0c-79a9-4eee-9962-e3634f9d627f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='account.languagePreference']</value>
      <webElementGuid>40ea3c07-fd0d-438c-91fa-37fea478b488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Catalog']/form/table[3]/tbody/tr/td[2]/select</value>
      <webElementGuid>392c4aee-fd87-454d-9940-bc22aba8dc4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language Preference:'])[1]/following::select[1]</value>
      <webElementGuid>50294a41-0045-46ff-9e92-4b5f6bcabb55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile Information'])[1]/following::select[1]</value>
      <webElementGuid>d6596ee5-cf87-46eb-bfa6-f57814f1e565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Favourite Category:'])[1]/preceding::select[1]</value>
      <webElementGuid>13badbc9-f3b7-4ea7-b94b-7fc8acf9a5dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable MyList'])[1]/preceding::select[2]</value>
      <webElementGuid>12f4d21e-f869-41bb-9755-3681d219ae75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>dd31fd9e-89dc-4f89-8886-35852599cf76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'account.languagePreference' and (text() = '
			englishjapanese
		' or . = '
			englishjapanese
		')]</value>
      <webElementGuid>02986a7f-63f6-4cdc-89ea-30fddbb0e23f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
