<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_FISHDOGSREPTILESCATSBIRDS</name>
   <tag></tag>
   <elementGuidId>e0e6e461-ce79-4988-af49-e9da14bc2912</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;account.favouriteCategoryId&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='account.favouriteCategoryId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7253c9f0-2d33-4468-a12d-53fd2d2c48e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account.favouriteCategoryId</value>
      <webElementGuid>3a3d6dd1-0e57-4623-b5d4-b29f986fd0ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			FISHDOGSREPTILESCATSBIRDS
		</value>
      <webElementGuid>92a0b257-64e0-4f11-a835-55d46bc0ed91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Catalog&quot;)/form[1]/table[3]/tbody[1]/tr[2]/td[2]/select[1]</value>
      <webElementGuid>b202c3fd-7f26-4de6-94c1-f30b3049f271</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='account.favouriteCategoryId']</value>
      <webElementGuid>dcfcc6a2-12ec-468a-a6b3-19361056e688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Catalog']/form/table[3]/tbody/tr[2]/td[2]/select</value>
      <webElementGuid>905a1f76-3038-41b1-8d97-b95f078b338e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Favourite Category:'])[1]/following::select[1]</value>
      <webElementGuid>a2ff74d3-a0ce-49f5-bad8-3b8dd284af1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language Preference:'])[1]/following::select[2]</value>
      <webElementGuid>8e570c0b-3020-4c1c-9e86-582c7352111c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable MyList'])[1]/preceding::select[1]</value>
      <webElementGuid>492c2e54-d05c-4ff3-9c18-092f5731b136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable MyBanner'])[1]/preceding::select[1]</value>
      <webElementGuid>76057755-907b-4808-b208-298a6b11260e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/select</value>
      <webElementGuid>97b5e620-a692-44d3-a1fd-3f7bf3d0081e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'account.favouriteCategoryId' and (text() = '
			FISHDOGSREPTILESCATSBIRDS
		' or . = '
			FISHDOGSREPTILESCATSBIRDS
		')]</value>
      <webElementGuid>c87a38a5-cb13-47d2-a952-c4b76ae85532</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
