<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>f63057e1-2041-473b-959b-bab14491bdc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-outline-dark.rounded.bg-white.m-1.w-100.text-uppercase.fs-6.px-0.fw-100.waves-effect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mynavbar']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d8892edf-afcc-441a-83fc-16a2cd751021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-dark rounded bg-white m-1 w-100 text-uppercase fs-6 px-0 fw-100 waves-effect</value>
      <webElementGuid>967f9181-8116-47c9-a870-892a403f9764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>feb3e757-1014-4a5e-ae7d-bb5aef069c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://phptravels.org</value>
      <webElementGuid>e1fdfe2a-81f8-4639-96b5-556271e24418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>04993bbe-cb1d-4b1d-aa29-104e8de6f3fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mynavbar&quot;)/div[@class=&quot;nav-right col-12 col-xl-3 my-2 my-xl-0 d-flex&quot;]/a[@class=&quot;btn btn-outline-dark rounded bg-white m-1 w-100 text-uppercase fs-6 px-0 fw-100 waves-effect&quot;]</value>
      <webElementGuid>d88f6295-ab7e-4c85-a4c4-8d5f18b82d2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mynavbar']/div/a</value>
      <webElementGuid>78ead806-8f61-438a-9275-8da6d4e6aa80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Media Kit'])[1]/following::a[1]</value>
      <webElementGuid>5e34ddaa-90cf-4de6-b733-5abd84334530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partners'])[1]/following::a[2]</value>
      <webElementGuid>001928d6-511e-44a9-b1af-496ade29d5b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Signup'])[1]/preceding::a[1]</value>
      <webElementGuid>a2f6de42-a145-41a1-972e-9e8977cd5f49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://phptravels.org')]</value>
      <webElementGuid>8ebaecb7-34f3-4dbc-8d80-dcf03412fe16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>e4f7fd35-db66-4f2b-a348-3c0ce3a20d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://phptravels.org' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>54a771de-dd39-425c-86de-5e7d32293325</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
