<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , chat-widget, , ))_chat-widget</name>
   <tag></tag>
   <elementGuidId>77a52aaf-8dda-4dc2-ba37-60086ec5d0a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chat-widget</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='chat-widget']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>0b2b1c10-06e1-4e02-b48a-d0e9f38c57fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay; microphone *; camera *; display-capture *; picture-in-picture *; fullscreen *;</value>
      <webElementGuid>82602896-9172-46c8-a605-0ec1a0cd026c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://secure.livechatinc.com/customer/action/open_chat?license_id=4618001&amp;group=0&amp;embedded=1&amp;widget_version=3&amp;unique_groups=0</value>
      <webElementGuid>1d115d46-1194-4bff-8f6f-fe7ab5a391b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bcca86c9-72a1-4d1d-b500-af080ee119ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chat-widget</value>
      <webElementGuid>11f4c8df-e70e-4ce6-a8bd-0a78557e8d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chat-widget</value>
      <webElementGuid>b6d7a536-b7fe-415a-8e13-e9d7929b6fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>LiveChat chat widget</value>
      <webElementGuid>34737fc7-62fb-44ec-a71c-d812da20cf9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>e76a7af8-292b-48d3-9d4f-048242b86837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chat-widget&quot;)</value>
      <webElementGuid>5d60a0be-67a9-4f16-b41c-ee1cf9f459af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='chat-widget']</value>
      <webElementGuid>1bea10a0-a610-4ca8-938f-da7730d40a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chat-widget-container']/iframe</value>
      <webElementGuid>19e3fac4-4547-441a-bbb5-8ab1afea9e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>a1c3fa2a-813a-4057-b120-d307a849daba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://secure.livechatinc.com/customer/action/open_chat?license_id=4618001&amp;group=0&amp;embedded=1&amp;widget_version=3&amp;unique_groups=0' and @id = 'chat-widget' and @name = 'chat-widget' and @title = 'LiveChat chat widget']</value>
      <webElementGuid>ed74db5b-2b9a-4e9f-a12d-b6f07516cd60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
