<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Home</name>
   <tag></tag>
   <elementGuidId>57fb9571-9a62-4755-aacd-12f2bf5c7d4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.pr-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='Primary_Navbar-Home']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>66d778a0-4647-449d-9a43-e01ce2774595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pr-4</value>
      <webElementGuid>f05c5715-647c-4f54-ac25-02368d21a281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php</value>
      <webElementGuid>c3bf3ef3-a0bf-4936-9d1b-14e80427cc5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Home
</value>
      <webElementGuid>66715b5c-9108-4d10-931d-35cfe47ad47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Primary_Navbar-Home&quot;)/a[@class=&quot;pr-4&quot;]</value>
      <webElementGuid>e8daf9bd-5c64-441a-9bf0-b28e0279d939</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='Primary_Navbar-Home']/a</value>
      <webElementGuid>3740c9aa-a635-49a2-8a7f-1d51db80893c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Home')]</value>
      <webElementGuid>9f6f7035-bf9b-4e72-a60e-f889c3eead41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shopping Cart'])[1]/following::a[1]</value>
      <webElementGuid>ff8e1f58-95fb-44e4-899e-9900e878bce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse All'])[1]/preceding::a[2]</value>
      <webElementGuid>4cb354cf-90a7-49c9-91cc-e871eb4c82df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Installation'])[1]/preceding::a[3]</value>
      <webElementGuid>fd94a4ec-05d0-4416-a18f-91e510bf4231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Home']/parent::*</value>
      <webElementGuid>c0739705-36f3-4dcf-b9fb-6fb6ae07e213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/index.php')])[2]</value>
      <webElementGuid>23d5be75-0e33-4c0f-94b5-89d639052ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li/a</value>
      <webElementGuid>99392dcf-2ee6-4050-b3a1-cfbbc320c4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php' and (text() = '
Home
' or . = '
Home
')]</value>
      <webElementGuid>9ba1ff95-e557-4c3c-8550-ebeab634ff4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
