<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Billing Address_address1</name>
   <tag></tag>
   <elementGuidId>af463645-cbfa-417a-a958-1f9528072170</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputAddress1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputAddress1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>591a4796-c8ea-4938-80e5-8be6fb4619e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3b0d3d53-a473-4306-b9f4-caedd84f32d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address1</value>
      <webElementGuid>ba8e23e9-fe2d-4fc6-b08c-884710d87807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputAddress1</value>
      <webElementGuid>935ee7f7-deca-4fb5-9a9f-c61b7fd3d616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field form-control</value>
      <webElementGuid>81f92f3a-bcaf-4ae7-a3c9-c15b193c98e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Street Address</value>
      <webElementGuid>46f87c16-2aef-4dcd-b8fc-333e5252dd6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputAddress1&quot;)</value>
      <webElementGuid>f9c0d6d8-64cb-4457-9495-998096efa274</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputAddress1']</value>
      <webElementGuid>c7cd92a4-93a0-44e4-b9db-4d675bc4e4f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='containerNewUserSignup']/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>fe8e217f-63c7-432e-a813-6ebdcdf55d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>1e628063-d5e0-444d-ad79-e78932b179bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'address1' and @id = 'inputAddress1' and @placeholder = 'Street Address']</value>
      <webElementGuid>f36e1438-07a5-48ab-b6f5-c1761e15dbce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
