<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Personal Information_lastname</name>
   <tag></tag>
   <elementGuidId>a15dbaf1-c921-4b05-b579-3b5c7459d518</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputLastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputLastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce59c2a1-b707-41dc-8cd4-9ab07b9b1cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b3d8043f-e8d8-45f3-9e6b-0f71b75d15c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastname</value>
      <webElementGuid>3b2e1a2d-1bc3-41f5-96bc-594982b50041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputLastName</value>
      <webElementGuid>1b0172a7-0c28-4756-9170-765483abe9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field form-control</value>
      <webElementGuid>6dc7f891-d6f6-407e-b39d-2754a24656a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>b57812b2-46ad-4cea-9b1c-175f589002bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputLastName&quot;)</value>
      <webElementGuid>4f7df4d2-6d06-47ef-b015-749f3b6fbe72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputLastName']</value>
      <webElementGuid>0cb50aa1-6121-461e-b4f9-b6728e1b4625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='containerNewUserSignup']/div/div/div/div[2]/div/input</value>
      <webElementGuid>ce1798f3-9943-44df-9a04-1cd97b3b741a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>ec4bc867-6480-471e-9765-9c761c65c3a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'lastname' and @id = 'inputLastName' and @placeholder = 'Last Name']</value>
      <webElementGuid>66381b77-e159-4fe0-83cc-5f52fcffa36f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
