<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password Length_inputGeneratePasswordLength</name>
   <tag></tag>
   <elementGuidId>ab8f3bda-849d-4281-b06a-bfd163e17c30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputGeneratePasswordLength</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputGeneratePasswordLength']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ede9d22-a0df-41e6-a0f4-a1f5e351a70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0cb02153-5d39-4567-afc0-bf84fc471a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>a9d839ed-8a03-44ff-ba05-e068ac0e1a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>2c3ad2cf-e458-4778-bc41-39cd8fe93887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>79441a95-c839-48dd-b5d6-76b92900185b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c3dbc44a-5950-44ed-bf54-750bf0b51a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-inline input-inline-100</value>
      <webElementGuid>0591a0b6-58d4-4372-8c2a-8daaf30e2dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputGeneratePasswordLength</value>
      <webElementGuid>08f85a60-ced8-4797-8e14-4bb8e3e3a843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputGeneratePasswordLength&quot;)</value>
      <webElementGuid>cd5a4ab2-2e16-4332-8532-9469fcae53c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputGeneratePasswordLength']</value>
      <webElementGuid>1621241e-3ab8-4f41-97b4-692e06ac9808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalGeneratePassword']/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>59e4b688-4ee8-428e-8fee-1f5fc3009a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>12a56cef-c0be-48eb-9049-b434712e295d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'inputGeneratePasswordLength']</value>
      <webElementGuid>5525b7c2-d919-41c9-b650-408e29c0ad57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
