<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Personal Information_firstname</name>
   <tag></tag>
   <elementGuidId>99e6ba4a-0f96-42e0-b27c-439a031095be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputFirstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputFirstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf855ca5-7f77-4f71-a9a6-5b40d7a8f2c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5292aba2-e06f-4956-8683-cf026b431405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstname</value>
      <webElementGuid>a1f9e95d-99b6-4214-b60a-edd770966bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputFirstName</value>
      <webElementGuid>f4c94170-cddf-488a-8878-2aec99dddeb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field form-control</value>
      <webElementGuid>1eeffd55-5a2c-4a30-8234-82b3e0ad3611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>2c251a72-82aa-45ae-9d6f-a67b8d5e075c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputFirstName&quot;)</value>
      <webElementGuid>8e46893e-d31c-4fcc-b4c4-a5875a558080</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputFirstName']</value>
      <webElementGuid>45f6c535-35fe-4336-a57c-fa8f28a8a4b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='containerNewUserSignup']/div/div/div/div/div/input</value>
      <webElementGuid>a1955a83-abf7-4ffe-b90a-d79628165b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>e165a111-7c44-4128-9537-9b09b2b32c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'firstname' and @id = 'inputFirstName' and @placeholder = 'First Name']</value>
      <webElementGuid>445eddad-706a-496f-8992-83516bbc1550</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
