<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_land Islands_phonenumber</name>
   <tag></tag>
   <elementGuidId>499e0b1d-e35e-4746-86c2-f9a85a6c19b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputPhone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputPhone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f667918a-4057-470f-832a-9c16deec8e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>3b4da7d3-638c-48d1-8f37-0e336f730380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phonenumber</value>
      <webElementGuid>4e0bcb9d-9e9a-4fce-97bb-a57f4b7807b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputPhone</value>
      <webElementGuid>a3f7fe56-7108-4505-bf5c-8e3a408fc922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>48e5eb78-f491-4c6c-9774-b691bd684c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Phone Number</value>
      <webElementGuid>60f578da-94bf-4468-a431-f4a44d874aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>46da3b7d-cbc4-4190-8dff-591ed58455de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputPhone&quot;)</value>
      <webElementGuid>ba1ec445-a781-4704-a416-f4f36d5681fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputPhone']</value>
      <webElementGuid>eb3ec364-1a3b-4634-badf-f5f713738dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='containerNewUserSignup']/div/div/div/div[4]/div/div/input</value>
      <webElementGuid>79300b33-23ae-4d86-8dfb-8e7ea363bd63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>c2b0e387-e5cc-4c73-9744-fb460e6f07f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'phonenumber' and @id = 'inputPhone' and @placeholder = 'Phone Number']</value>
      <webElementGuid>9d1e9ea7-7edb-40d0-862a-604690937d69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
