<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Billing Address_postcode</name>
   <tag></tag>
   <elementGuidId>7361dcdc-2afe-4640-8037-a70bb0940e71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputPostcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputPostcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7880a004-e8d1-4f40-9ff9-fb6590b240d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3420d72c-f93b-40e1-a806-b5433337d6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>postcode</value>
      <webElementGuid>c0ecb71e-3110-4596-a285-da55d13b4c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputPostcode</value>
      <webElementGuid>57f35838-663c-4783-9913-793f0cbe4cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field form-control</value>
      <webElementGuid>9c97c21b-2fc7-4403-84ac-f62781d0df24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Postcode</value>
      <webElementGuid>2373b12c-5f77-4ff2-bf1a-6dd2d12620c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputPostcode&quot;)</value>
      <webElementGuid>d63a671d-2dbe-4f3a-a44f-04b3e9c47b66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputPostcode']</value>
      <webElementGuid>8d461c48-4405-4a2e-80f3-70ae0666d626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='containerNewUserSignup']/div[2]/div/div/div[6]/div/input</value>
      <webElementGuid>8483bbb5-bead-4e3d-8024-3f11c0a7d54e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>566b39bb-40d7-4955-9f1a-e19e02bb8426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'postcode' and @id = 'inputPostcode' and @placeholder = 'Postcode']</value>
      <webElementGuid>c59e05d3-28b6-40ad-8bbf-fac6e8f06952</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
