<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Generated Password_inputGeneratePassw_1aa1a9</name>
   <tag></tag>
   <elementGuidId>43a565bc-efda-4c26-96cd-c5a2b043b450</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputGeneratePasswordOutput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputGeneratePasswordOutput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1854be86-9bd1-4f3e-be3d-8cd20f7f32d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eb144f7f-7ab8-4eba-99e6-420208949838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>07b163d3-cdc8-45d4-969e-86f9d8ce161d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputGeneratePasswordOutput</value>
      <webElementGuid>c376a2a3-afbd-4716-9a33-9f34b9a0dc96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputGeneratePasswordOutput&quot;)</value>
      <webElementGuid>60a4fbca-f438-4041-a69f-f653f6962e36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputGeneratePasswordOutput']</value>
      <webElementGuid>ad1ecb52-4b23-4cf5-a938-46633fd1bd0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalGeneratePassword']/div/div/div[2]/div[3]/div/input</value>
      <webElementGuid>cdfbdffd-ae7d-4320-9496-bd74cb287cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/input</value>
      <webElementGuid>39d4a266-d9f8-483d-93af-3b05788f17e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputGeneratePasswordOutput']</value>
      <webElementGuid>e4208f86-a9aa-4b2b-8b5f-e2516e28d51c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
