<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Signup</name>
   <tag></tag>
   <elementGuidId>7162628a-2aa4-478b-a91a-ae196758b78b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.rounded.m-1.w-100.text-uppercase.fs-6.px-0.waves-effect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mynavbar']/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>73ff87a8-9e84-4164-8377-f950e5ff96e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary rounded m-1 w-100 text-uppercase fs-6 px-0 waves-effect</value>
      <webElementGuid>f4111cd9-6045-4e2a-a087-eefaa7c6e6fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>8f7fedbf-615a-4d38-adca-6ed429185d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://phptravels.org/register.php</value>
      <webElementGuid>8deb9ac1-0ac8-4179-b6b8-cfa940af9350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Signup</value>
      <webElementGuid>0571264f-0a85-4bd8-8988-274b2c86a5d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mynavbar&quot;)/div[@class=&quot;nav-right col-12 col-xl-3 my-2 my-xl-0 d-flex&quot;]/a[@class=&quot;btn btn-primary rounded m-1 w-100 text-uppercase fs-6 px-0 waves-effect&quot;]</value>
      <webElementGuid>9bc250d6-34c7-4c4a-a845-877a91fcb7c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mynavbar']/div/a[2]</value>
      <webElementGuid>a0828c73-c202-4e87-84b8-fa7c3b33972f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::a[1]</value>
      <webElementGuid>1f6c198a-fac1-4a43-9041-4be229fde5a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Media Kit'])[1]/following::a[2]</value>
      <webElementGuid>9eef1bc5-16ac-45bf-8730-6b9af24c4d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demonstration'])[1]/preceding::a[1]</value>
      <webElementGuid>07f08b05-f777-4d04-9f6e-6f50bb122932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://phptravels.org/register.php')]</value>
      <webElementGuid>7281b913-0c10-4a10-b841-161aac525a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>08accfb5-c997-4a56-bb6b-f46fb610f6d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://phptravels.org/register.php' and (text() = 'Signup' or . = 'Signup')]</value>
      <webElementGuid>c4aee23f-750c-4389-8f64-6ffc0dd3c5ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
