<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bags</name>
   <tag></tag>
   <elementGuidId>f4a14afc-1064-4f23-9a52-a12ce2c5ac09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ol.items > li.item > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//dl[@id='narrow-by-list2']/dd/ol/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4a7d4e12-8539-4c15-aa66-9b302a9f97c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://magento.softwaretestingboard.com/gear/bags.html</value>
      <webElementGuid>f2147d0d-2831-4a33-937d-2be87310b4e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bags</value>
      <webElementGuid>b4970310-ce8f-48c5-9f17-a9e6a72560ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;narrow-by-list2&quot;)/dd[1]/ol[@class=&quot;items&quot;]/li[@class=&quot;item&quot;]/a[1]</value>
      <webElementGuid>41a718a8-a000-4668-9c2f-48b3719c2d86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dl[@id='narrow-by-list2']/dd/ol/li/a</value>
      <webElementGuid>d30ece3e-e041-478d-ba37-1fdec2ef3ba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bags')]</value>
      <webElementGuid>5bb1f21d-f66e-4820-8f32-5c4cf2482cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/following::a[1]</value>
      <webElementGuid>9511dffc-eb15-4991-b19d-2f1172a8518d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shopping Options'])[1]/following::a[1]</value>
      <webElementGuid>79dad436-651b-4082-9bf6-9fc7b0e21157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fitness Equipment'])[2]/preceding::a[1]</value>
      <webElementGuid>ae292bcf-4187-4fcd-8929-4e962d1223d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watches'])[2]/preceding::a[2]</value>
      <webElementGuid>b0a00d93-325e-471b-8cf3-1d9636ccdd30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://magento.softwaretestingboard.com/gear/bags.html')])[3]</value>
      <webElementGuid>b4057b1b-d647-489d-831c-ba761798f3b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li/a</value>
      <webElementGuid>40ea0803-938a-4798-8197-e3102c68360f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://magento.softwaretestingboard.com/gear/bags.html' and (text() = 'Bags' or . = 'Bags')]</value>
      <webElementGuid>06a1d483-249d-4aee-ae55-5eca054f116d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
