<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tops</name>
   <tag></tag>
   <elementGuidId>210daef5-3297-476a-a509-982e8f8be583</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ol.items > li.item > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//dl[@id='narrow-by-list2']/dd/ol/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>678bb52b-3870-4826-9736-81512142e645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://magento.softwaretestingboard.com/women/tops-women.html</value>
      <webElementGuid>597558b4-b9b9-476c-9313-d4ee6afbf8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tops</value>
      <webElementGuid>a7707bbb-dd8b-4811-b588-15796bedf2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;narrow-by-list2&quot;)/dd[1]/ol[@class=&quot;items&quot;]/li[@class=&quot;item&quot;]/a[1]</value>
      <webElementGuid>7c4e549a-3ba6-4a19-9aec-a0d47b12e08f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dl[@id='narrow-by-list2']/dd/ol/li/a</value>
      <webElementGuid>3d62d05e-ccf8-42e4-b68d-6915bff3249c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tops')]</value>
      <webElementGuid>77c0ce3e-2d3e-4c92-a73a-5cec0cc8e912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/following::a[1]</value>
      <webElementGuid>cb80c1a5-ee7c-4628-bfe9-f887117e8da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shopping Options'])[1]/following::a[1]</value>
      <webElementGuid>388622fe-eefe-4a25-a0d2-7c9f3e16f067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bottoms'])[3]/preceding::a[1]</value>
      <webElementGuid>0ca569a6-4e6c-46cc-af9d-a52d03d9d7f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tops'])[4]/preceding::a[2]</value>
      <webElementGuid>30593cd4-948c-47d5-9dd2-8505f34273a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://magento.softwaretestingboard.com/women/tops-women.html')])[2]</value>
      <webElementGuid>74989f31-2af6-4b4d-8623-b4bf44a14205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li/a</value>
      <webElementGuid>6c2399f6-d701-4a46-b1a4-1daf3fa6164e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://magento.softwaretestingboard.com/women/tops-women.html' and (text() = 'Tops' or . = 'Tops')]</value>
      <webElementGuid>2da1a0a5-9ca2-40b6-9fc4-8557b6112d43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
