<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reviews 3</name>
   <tag></tag>
   <elementGuidId>afe888eb-786b-4f5b-b7ae-d177afcfb2a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-label-reviews-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='tab-label-reviews-title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f219077f-ff54-4149-ad6c-f3ce345f37b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>data switch</value>
      <webElementGuid>7dedc67a-58eb-4071-85d4-69d455bbc6d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f4a3f94e-af70-4776-bd16-9886f22dd7ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>trigger</value>
      <webElementGuid>ba7f5032-acb7-4fd9-8544-d24c30e4d475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#reviews</value>
      <webElementGuid>5fb1b313-b1e4-4ab0-90fb-81f0f99d355f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-label-reviews-title</value>
      <webElementGuid>54c5db7a-7791-4a70-90f6-13e9443b7e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Reviews 3 </value>
      <webElementGuid>dcf8cea6-3a6f-442e-a815-eb8fd5a0782b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-label-reviews-title&quot;)</value>
      <webElementGuid>873f9343-60b3-47d8-86ab-b34072cfea0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='tab-label-reviews-title']</value>
      <webElementGuid>801a2945-53d0-46d2-8f33-797b875e53ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-label-reviews']/a</value>
      <webElementGuid>2d54de2b-34c9-4aaa-af08-7048018118ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waterproof, Lightweight, Laptop Sleeve, Lockable'])[1]/following::a[1]</value>
      <webElementGuid>83cfa4c6-46d6-4420-89d1-10b425e7c03b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Features'])[1]/following::a[1]</value>
      <webElementGuid>ad49d0d6-3b70-47b6-ae35-ca66c5c8eade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Write Your Own Review'])[1]/preceding::a[1]</value>
      <webElementGuid>4a04f345-4b37-49f1-bedd-26f48dd9c0fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('You', &quot;'&quot;, 're reviewing:')])[1]/preceding::a[1]</value>
      <webElementGuid>adbc8681-d335-4110-a3d5-e764887441ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#reviews')])[2]</value>
      <webElementGuid>a05c66d2-2d22-4b77-964e-cc486dedd263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>1fa5db23-d58e-4ef0-9417-32c756424a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#reviews' and @id = 'tab-label-reviews-title' and (text() = '
Reviews 3 ' or . = '
Reviews 3 ')]</value>
      <webElementGuid>4bfd92a3-b286-4953-8e8e-18c721512ec6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
