<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Shopping Cart_logo-img</name>
   <tag></tag>
   <elementGuidId>c41ca45e-d42e-40ce-9286-be5a5fb52605</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.logo-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>87427c15-ce29-4c55-8e7a-c89bd9a28f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/img/logo.png</value>
      <webElementGuid>0cb3d079-a606-4249-8dc4-2e50e293f995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>PHPTRAVELS</value>
      <webElementGuid>e6ba6365-6c80-48c9-bedb-290aa32b586a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo-img</value>
      <webElementGuid>35ca0d14-3d3d-432c-b864-d98982867d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;navbar navbar-light&quot;]/div[@class=&quot;container&quot;]/a[@class=&quot;navbar-brand mr-3&quot;]/img[@class=&quot;logo-img&quot;]</value>
      <webElementGuid>814c1f1c-0720-4c8f-911a-e6030a0ac802</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/div/a/img</value>
      <webElementGuid>86a09ea2-e44b-4553-b216-109d2948fc75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='PHPTRAVELS']</value>
      <webElementGuid>0fda17e8-b7fb-4935-bfcc-c411a3c47f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>888b8289-756a-4a03-8e04-f180dbbf9a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/img/logo.png' and @alt = 'PHPTRAVELS']</value>
      <webElementGuid>b6192c45-7d6a-4911-aabb-4f9b94a19fc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
