<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Downloads</name>
   <tag></tag>
   <elementGuidId>60aa8ecd-9047-4118-a6e9-a3d79ccee595</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Secondary_Sidebar-Support-Downloads</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Secondary_Sidebar-Support-Downloads']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>35b0b44e-9859-4862-8787-e2e866f1b4ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>menuitemname</name>
      <type>Main</type>
      <value>Downloads</value>
      <webElementGuid>2307d173-31a8-4874-adee-1494e420effc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/download</value>
      <webElementGuid>0d2d1ea3-4ba5-47fb-aa2e-eb1251615a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item list-group-item-action</value>
      <webElementGuid>18c4c240-9ea7-4724-a5c5-65c624f7f51e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Secondary_Sidebar-Support-Downloads</value>
      <webElementGuid>ff7978e7-23ab-4df8-bed4-848f2b492a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  Downloads
</value>
      <webElementGuid>44280309-374d-4d66-a186-657b6082302d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-body&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-4 col-xl-3&quot;]/div[@class=&quot;d-none d-lg-block sidebar&quot;]/div[@class=&quot;mb-3 card card-sidebar&quot;]/div[@class=&quot;collapsable-card-body&quot;]/div[@class=&quot;list-group list-group-flush d-inline-block d-md-flex&quot;]/a[@id=&quot;Secondary_Sidebar-Support-Downloads&quot;]</value>
      <webElementGuid>7fb0b420-046d-4da3-bd70-5ecd436040f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='Secondary_Sidebar-Support-Downloads']</value>
      <webElementGuid>3361a349-5a9d-4866-be60-5aa2430d2ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-body']/div/div/div/div[2]/div/div[2]/div/a[4]</value>
      <webElementGuid>c05a2fae-de76-42bb-8c38-dfdb7506200a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/download')]</value>
      <webElementGuid>687c0a61-2fb5-438a-9c7e-005191b65f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>20ba8314-c7ee-4565-8735-0cad5cbc98e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/download' and @id = 'Secondary_Sidebar-Support-Downloads' and (text() = '
  Downloads
' or . = '
  Downloads
')]</value>
      <webElementGuid>32df3e2e-81bb-4862-bd74-a4459b453b78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
