<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>ddc5bbef-e696-4a8a-8023-21944d50e965</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='LogoContent']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c5c7c62b-4e03-43f8-90a7-bce52556348c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/logo-topbar.gif</value>
      <webElementGuid>fffe0b5f-41b4-4700-8639-09460e148944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LogoContent&quot;)/a[1]/img[1]</value>
      <webElementGuid>469822e9-1f6e-403e-855f-d0a46dfef1c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LogoContent']/a/img</value>
      <webElementGuid>3531b9ef-72b3-45ee-8951-e4bba9008c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>3eb9fb7e-a5d9-4797-9b3a-7e7fbec9d300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images/logo-topbar.gif']</value>
      <webElementGuid>4a79ddd3-81e4-49b4-83c7-4dfa8adafc64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
