<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Shopping Cart_fas fa-search</name>
   <tag></tag>
   <elementGuidId>9438b4f4-d06a-4d1b-83e6-e0da020cb20d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div/div/form/div/div/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>5cd190ee-ebfd-4c39-ab49-eff66a372b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-search</value>
      <webElementGuid>0e52b17a-6d21-4680-850e-cd40e085a568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;navbar navbar-light&quot;]/div[@class=&quot;container&quot;]/form[@class=&quot;form-inline ml-auto&quot;]/div[@class=&quot;input-group search d-none d-xl-flex&quot;]/div[@class=&quot;input-group-prepend&quot;]/button[@class=&quot;btn btn-default&quot;]/i[@class=&quot;fas fa-search&quot;]</value>
      <webElementGuid>4e4c4088-3ff9-4967-a068-06e7298db646</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/div/form/div/div/button/i</value>
      <webElementGuid>1a833f51-b7de-4982-bc74-07c860a74dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>9fdc796c-9b2d-42e0-a68b-61a6f40ca1c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
