<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Email Address_a-45x1it6fa0c9</name>
   <tag></tag>
   <elementGuidId>c7b25179-a8d5-49a5-9e53-95182cb986be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-45x1it6fa0c9&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-45x1it6fa0c9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>97b5e5e6-af27-4e36-8c70-ba5121a9592d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>08e67dd1-72b9-4a44-ae03-6d5e5f81c749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>4a16d470-5662-48f8-a2c3-92b1c88b355f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>a1f786bf-17ea-4cf4-8307-633ab5387e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>fc50b01e-f222-4d14-a2f0-d553b9bc436c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-45x1it6fa0c9</value>
      <webElementGuid>12cbcb3f-8930-491a-9403-2125e655f438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f7f76db3-5b56-4a84-a15d-5e88a6c3c11e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>8aaf0bfa-6f70-4612-a906-3a32264d1614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>a89a3309-ca29-4961-8467-a971ff359bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdJtY8UAAAAADTgIWYnG_VKkfNqqB-w8CdQFL7Y&amp;co=aHR0cHM6Ly9waHB0cmF2ZWxzLm9yZzo0NDM.&amp;hl=en&amp;v=-QbJqHfGOUB8nuVRLvzFLVed&amp;size=normal&amp;cb=qw68l8ngo4zj</value>
      <webElementGuid>aba409b0-e85e-4c1b-a9e4-9a51bdc8f8fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;#divDynamicRecaptcha1&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>86878c5d-3ca2-4351-98fd-9df84b762bcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-45x1it6fa0c9']</value>
      <webElementGuid>85a6124d-1bb9-4b88-8ce0-1c84a3fd425e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='#divDynamicRecaptcha1']/div/div/iframe</value>
      <webElementGuid>c6549e0a-a891-4457-a381-ef87f0ed8954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>6abf5579-44db-4f72-9a6d-441befece54b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-45x1it6fa0c9' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdJtY8UAAAAADTgIWYnG_VKkfNqqB-w8CdQFL7Y&amp;co=aHR0cHM6Ly9waHB0cmF2ZWxzLm9yZzo0NDM.&amp;hl=en&amp;v=-QbJqHfGOUB8nuVRLvzFLVed&amp;size=normal&amp;cb=qw68l8ngo4zj']</value>
      <webElementGuid>c96073f1-f4c5-4fcc-9637-b31ebf92d84d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
