<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Im not a robot</name>
   <tag></tag>
   <elementGuidId>46f2cd8e-9175-438b-a1d0-c1d393fb7383</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#recaptcha-anchor-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='recaptcha-anchor-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>abc6b455-ab0e-47a5-8ae9-649738cc8148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-anchor-center-item rc-anchor-checkbox-label</value>
      <webElementGuid>c1852a40-70e6-4014-9fa2-51916adb68bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>73c92556-d728-4da8-b3dd-d06355afb998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>752bfef7-f557-4c97-b33e-3879a67257cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recaptcha-anchor-label</value>
      <webElementGuid>ad20039c-204a-474f-9e95-2a15aca4b064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I'm not a robot</value>
      <webElementGuid>47be31f6-50bb-41e7-9923-338a0a371d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha-anchor-label&quot;)</value>
      <webElementGuid>d2aabedd-83e6-492b-ac10-af5ea2a4b8d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/LoginPage/Page_Lost Password Reset - PHPTRAVELS/iframe_Email Address_a-45x1it6fa0c9</value>
      <webElementGuid>d84c2187-61d9-458c-9563-5e1049db9e96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='recaptcha-anchor-label']</value>
      <webElementGuid>62904600-bf05-4c4a-9176-fc2aadfdfa62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-anchor-container']/div[3]/div[2]/div/label</value>
      <webElementGuid>8b8073c3-d24f-4274-b766-5ce102dabfe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='reCAPTCHA'])[2]/preceding::label[1]</value>
      <webElementGuid>7a38b0f6-ccd6-4bdc-b56b-66ae4d8bb733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy'])[1]/preceding::label[1]</value>
      <webElementGuid>8365c8e9-34a0-4a84-9cd1-8281be7fee35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>36f29ab1-f0bd-4632-b942-21c8a91b8835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'recaptcha-anchor-label' and (text() = concat(&quot;I&quot; , &quot;'&quot; , &quot;m not a robot&quot;) or . = concat(&quot;I&quot; , &quot;'&quot; , &quot;m not a robot&quot;))]</value>
      <webElementGuid>fee442d8-a38d-4f36-a7d7-deca99087acf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
