<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Added to Cart (Remove)</name>
   <tag></tag>
   <elementGuidId>637e7e6d-4584-43c1-982c-ccaba3ea5b9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.panel-add</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmConfigureProduct']/div/div/div[4]/div/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2906e5c1-4e80-4811-8e43-8f0ec898be30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-add</value>
      <webElementGuid>73d66a2d-647b-4202-8c75-aba71ddb0480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Added to Cart (Remove)</value>
      <webElementGuid>d09b3c74-16a5-489a-8c36-fa7fcd4195fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmConfigureProduct&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;secondary-cart-body&quot;]/div[@class=&quot;row addon-products&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;panel card panel-default panel-addon panel-addon-selected&quot;]/div[@class=&quot;panel-add&quot;]</value>
      <webElementGuid>51a29352-d613-4a07-9ee0-dae4a18ce293</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmConfigureProduct']/div/div/div[4]/div/div/div[3]</value>
      <webElementGuid>3b1616a8-3b5a-4e65-9d59-b08bbda37a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$300.00 USD One Time'])[1]/following::div[1]</value>
      <webElementGuid>492346fc-5b80-4aae-bddb-ded3bc44020d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click here'])[1]/preceding::div[1]</value>
      <webElementGuid>0272c512-8920-4132-a53a-cb812a8500cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Added to Cart (Remove)']/parent::*</value>
      <webElementGuid>8f876a1a-f2c5-4df3-91e9-435f4af70797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]</value>
      <webElementGuid>6b640096-7b0a-4b41-9841-4dc29c0ebb22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Added to Cart (Remove)' or . = ' Added to Cart (Remove)')]</value>
      <webElementGuid>206e08c8-0610-45cb-9dec-ccf1bfbfcfa1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
