<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Domain Name_customfield12</name>
   <tag></tag>
   <elementGuidId>f875598d-e08e-43a7-a3cd-c6c8e88f7b80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customfield12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customfield12']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2665f82-a1c5-47d1-8cf8-045cae74db6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>06566d91-e3ca-43dd-86f6-41020626a950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customfield[12]</value>
      <webElementGuid>e927745c-4306-4716-8218-271b7d29ddce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customfield12</value>
      <webElementGuid>a0e4d5b6-b001-4ffe-b1e2-666013975631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>aae664e3-78b0-46ec-bf84-5defa51f5a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>69a9556f-997f-45ab-803f-42a4ae15a2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customfield12&quot;)</value>
      <webElementGuid>aa235b99-8506-4815-a59f-d7342855d7e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customfield12']</value>
      <webElementGuid>46347c88-adb6-4abb-9463-c82cb86b66d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmConfigureProduct']/div/div/div[4]/div/input</value>
      <webElementGuid>a57d0a82-028d-4838-93cc-bba0e6e5183a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>0f512985-4642-4d93-8de0-034ea4592f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'customfield[12]' and @id = 'customfield12']</value>
      <webElementGuid>86526dba-75a7-48ab-86c6-ef51b7deebe8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
