<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ins_Uploading Apps to Stores_iCheck-helper_1</name>
   <tag></tag>
   <elementGuidId>129a2f3e-1710-4ad2-83ef-92774e1df449</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ins.iCheck-helper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmConfigureProduct']/div/div/div[4]/div/div/div/label/div/ins</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ins</value>
      <webElementGuid>b27b3e75-5d6d-4e72-a283-b453e5b98b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iCheck-helper</value>
      <webElementGuid>60e043af-99dc-4354-b29a-b59b15f98d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmConfigureProduct&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;secondary-cart-body&quot;]/div[@class=&quot;row addon-products&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;panel card panel-default panel-addon&quot;]/div[@class=&quot;panel-body card-body&quot;]/label[@class=&quot;hover&quot;]/div[@class=&quot;icheckbox_square-blue hover&quot;]/ins[@class=&quot;iCheck-helper&quot;]</value>
      <webElementGuid>2544c8d9-a141-4619-ab59-bbdf60e91c97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmConfigureProduct']/div/div/div[4]/div/div/div/label/div/ins</value>
      <webElementGuid>8f3f02e1-c28d-45af-8c3a-845e6b5f74e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ins</value>
      <webElementGuid>47c50ea8-e592-45d5-ab4d-527b3106d4c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
