<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ins_Uploading Apps to Stores_iCheck-helper</name>
   <tag></tag>
   <elementGuidId>1feec2b0-4a80-4cb3-a7fd-8f1f47760f96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ins.iCheck-helper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmConfigureProduct']/div/div/div[4]/div/div/div/label/div/ins</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ins</value>
      <webElementGuid>8fa608e4-4920-4161-88d0-a82467200baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iCheck-helper</value>
      <webElementGuid>f71a0129-bd44-43e4-a3a2-0e788b290b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmConfigureProduct&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;secondary-cart-body&quot;]/div[@class=&quot;row addon-products&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;panel card panel-default panel-addon&quot;]/div[@class=&quot;panel-body card-body&quot;]/label[@class=&quot;hover&quot;]/div[@class=&quot;icheckbox_square-blue focus hover&quot;]/ins[@class=&quot;iCheck-helper&quot;]</value>
      <webElementGuid>5c68f954-97ae-4374-9ba9-ffbab94be460</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmConfigureProduct']/div/div/div[4]/div/div/div/label/div/ins</value>
      <webElementGuid>74dcddba-d518-4155-8eee-b2c1322c1afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ins</value>
      <webElementGuid>6c0d1bec-168d-435e-9d39-1d7260d46bab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
