<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sub Total 18.50_updateCartQuantities</name>
   <tag></tag>
   <elementGuidId>8ac58f0d-43b3-4e45-9738-8e325ee401e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;updateCartQuantities&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='updateCartQuantities']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80b3bf80-cec3-44a3-a8a6-cf81b8a5de5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>updateCartQuantities</value>
      <webElementGuid>b2a559bf-7c73-46c2-acb2-0b78d5175a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>20c5149f-ace3-49db-aedd-aedf4521d8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Update Cart</value>
      <webElementGuid>5080543f-589f-4d12-b9d5-6cdf2c7d8678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Cart&quot;)/form[1]/table[1]/tbody[1]/tr[3]/td[1]/input[1]</value>
      <webElementGuid>b626b639-a6b9-47d3-86d8-1d46004f7dff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='updateCartQuantities']</value>
      <webElementGuid>c95be39a-4026-4a85-8b45-5d0ea967bde6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Cart']/form/table/tbody/tr[3]/td/input</value>
      <webElementGuid>e35d846e-aa88-44be-8508-7724a542ee27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/input</value>
      <webElementGuid>dc8fd8c1-f4b6-47fa-9511-89beceafbee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'updateCartQuantities' and @type = 'submit']</value>
      <webElementGuid>702aa320-eb6e-44cd-973d-ec35c1c0edf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
