<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Computer database</name>
   <tag></tag>
   <elementGuidId>e8b5567c-7d2b-4825-b89c-55e2339ccc3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.fill</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Computer database')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>79bcccb2-4780-4d5d-b5e9-f4f77fb2c0c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>984ba846-5ca0-4dbb-8b16-d624e8fa62de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/computers</value>
      <webElementGuid>c35d7c98-ad46-4a0c-aa7b-26a2091ab602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Computer database</value>
      <webElementGuid>e8703158-3f08-4965-9d19-b9379941bb6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[@class=&quot;topbar&quot;]/h1[@class=&quot;fill&quot;]/a[@class=&quot;fill&quot;]</value>
      <webElementGuid>dab86130-6e64-4b20-8b81-9d9a92988783</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Computer database')]</value>
      <webElementGuid>e5f92100-1bf5-4bb2-a95f-d5691b7b37b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done !'])[1]/preceding::a[1]</value>
      <webElementGuid>50b6d1da-f96f-45a0-9370-f945ff8c58e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Computer database']/parent::*</value>
      <webElementGuid>f466f861-f4e6-4278-8269-b6a89f7925d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/computers')]</value>
      <webElementGuid>35691705-8bc8-4f1b-ac85-5e680f4dfddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>7a1506a2-26c7-4fe0-8fad-282db8786b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/computers' and (text() = 'Computer database' or . = 'Computer database')]</value>
      <webElementGuid>47030c82-ed69-4fc3-9124-77e5a85154a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
