<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Computer database_searchsubmit</name>
   <tag></tag>
   <elementGuidId>63534358-c3f8-4df2-a9c6-baee059ffe99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchsubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchsubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a32f0b0f-efe6-4e98-af1a-83cb316e8f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>86130e83-7dc7-4ca8-9732-2cc2f37d92a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchsubmit</value>
      <webElementGuid>7e5d988b-dc68-4b6d-912b-e14c3d394942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Filter by name</value>
      <webElementGuid>b2016952-9beb-4b0b-9c73-d0e0e2c65b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn primary</value>
      <webElementGuid>bc73a60b-0e54-4cae-9648-a1762311654e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchsubmit&quot;)</value>
      <webElementGuid>d936691f-d2f9-4e9b-81fc-795b3a395a5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchsubmit']</value>
      <webElementGuid>74efc85b-2b77-4a73-b5d5-9d6e407acfea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='actions']/form/input[2]</value>
      <webElementGuid>82689349-9e15-40dd-8ccb-2a30bf000956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>2d5a93d1-0436-4d54-90d1-1c2f37231bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'searchsubmit']</value>
      <webElementGuid>81cb00c8-d4b7-4e65-a639-f88dbf09302e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
