<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_45.00</name>
   <tag></tag>
   <elementGuidId>2f3b14bc-b185-4c81-a9c0-8e90f1d1dbbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='product-price-14']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2bffe8ab-7f96-4da4-ba7c-ca8d82c6fa0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>f6b5d07a-e220-4475-9a48-c27cecd4dac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$45.00</value>
      <webElementGuid>a24eef0d-0401-42fc-9522-8bf7a3c8ce9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-price-14&quot;)/span[@class=&quot;price&quot;]</value>
      <webElementGuid>b3cc0c55-8ef7-4600-b9f4-247c149a51d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='product-price-14']/span</value>
      <webElementGuid>729e077d-c7fd-4e0a-a6d7-963df21e365f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reviews'])[1]/following::span[3]</value>
      <webElementGuid>e5e4446a-ac51-44ed-b761-d426449c07ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rating:'])[1]/following::span[6]</value>
      <webElementGuid>cb1ca9d2-7975-455b-a592-0747429bdbe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Cart'])[1]/preceding::span[1]</value>
      <webElementGuid>981d9f80-0573-40bb-8ec9-36b413307196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Wish List'])[1]/preceding::span[2]</value>
      <webElementGuid>cdf37186-21ab-49a9-ab7e-b6d4ea9bcbd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$45.00']/parent::*</value>
      <webElementGuid>23dd1dea-872b-4b80-b11c-32e562215353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span</value>
      <webElementGuid>33ac022a-98e2-40ec-b661-0f2b990bf87b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$45.00' or . = '$45.00')]</value>
      <webElementGuid>4f007ea5-ea1c-4a0a-94ea-8ddf5c04a6ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
