<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Return to RP-LI-02</name>
   <tag></tag>
   <elementGuidId>568be5cd-f0cb-4ae8-95cc-0e5c218ed08f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BackLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='BackLink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6822c213-c913-4e52-94b7-7efa88479df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BackLink</value>
      <webElementGuid>3bbcddb9-cf3a-42aa-941b-fb2f1583e903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Return to RP-LI-02</value>
      <webElementGuid>d057bc68-eca1-46cd-a616-59431c06b62b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BackLink&quot;)</value>
      <webElementGuid>089c2479-03b1-4f9d-a3b2-d2bfd93ab270</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='BackLink']</value>
      <webElementGuid>22bc5f80-973f-4b67-946b-863cc6b4f1b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Content']/div</value>
      <webElementGuid>90c6d949-7f5c-4a03-b921-f5ca1d80ed06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='?'])[1]/following::div[6]</value>
      <webElementGuid>7cbdc9bf-fc7b-44e7-b83d-66ac1da2bb52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/following::div[6]</value>
      <webElementGuid>96b41792-b726-454b-acdd-c53253de798b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Friendly green friend'])[1]/preceding::div[1]</value>
      <webElementGuid>c0f55790-3988-4901-8783-320fdd0b2c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>ae822d70-ee49-443d-b759-2ecf37a3e411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'BackLink' and (text() = 'Return to RP-LI-02' or . = 'Return to RP-LI-02')]</value>
      <webElementGuid>19fceab7-0e4f-4d40-a652-0a2428054432</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
